# Generated by Django 5.0.6 on 2025-02-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_user_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_query',
            old_name='email',
            new_name='Q_email',
        ),
    ]
