# Generated by Django 5.0.6 on 2025-02-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_email_user_query_q_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_query',
            name='user',
        ),
    ]
