# Generated by Django 5.0.6 on 2025-02-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_user_query_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='suggestion',
            field=models.TextField(null=True),
        ),
    ]
